gen:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  image: silex/emacs:29-ci-cask
  stage: build
  script:
    - make defs
  artifacts:
    paths:
      - cfn-mode/cfn-properties.dat
      - cfn-mode/cfn-resources.dat

commit:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  image: silex/emacs:29-ci-cask
  stage: deploy
  before_script:
    - git config --global user.name "GitLab Auto Committer"
    - git config --global user.email "noreply@worrbase.com"
    - git config --global push.autoSetupRemote true
    - git remote set-url origin https://worr:${API_TOKEN}@${CI_REPOSITORY_URL#*@}
  script:
    - git switch -c auto/$(date +%s)
    - git add cfn-mode/cfn-resources.dat cfn-mode/cfn-properties.dat
    - "git commit -m 'AUTO: Updating definitions'"
    - git push -o merge_request.create -o merge_request.merge_when_pipeline_succeeds -o merge_request.remove_source_branch
