default:
  image: silex/emacs:27
  before_script:
    - chmod +x run-tests.sh

lint 27:
  script: ./run-tests.sh

lint 26:
  script: ./run-tests.sh
  image: silex/emacs:26

lint 25:
  script: ./run-tests.sh
  image: silex/emacs:25
