lint cfn-mode:
  image: silex/emacs:$VERSION-ci-cask
  stage: test
  script:
    - cd cfn-mode
    - make deps
    - make lint
  parallel:
    matrix:
      - VERSION: 26
      - VERSION: 27
      - VERSION: 28
      - VERSION: 29
      - VERSION: master

lint flycheck-cfn:
  image: silex/emacs:$VERSION-ci-cask
  stage: test
  script:
    - cd flycheck-cfn
    - make deps
    - make lint
  parallel:
    matrix:
      - VERSION: 26
      - VERSION: 27
      - VERSION: 28
      - VERSION: 29
      - VERSION: master

# only lint this in emacs29. it's dev-only so compat doesn't matter
lint cfn-gen:
  image: silex/emacs:29-ci-cask
  stage: test
  script:
    - cd cfn-gen
    - make deps
    - make lint
