lint:
  image: silex/emacs:$VERSION-ci-cask
  stage: test
  script:
    - cd $PROJ
    - make deps
    - make lint
  parallel:
    matrix:
      - VERSION: [26, 27, 28, 29, master]
        PROJ: [cfn-mode, flycheck-cfn]
  rules:
    - if: $VERSION == "master"
      allow_failure: true
    - if: $VERSION

# only lint this in emacs29. it's dev-only so compat doesn't matter
lint cfn-gen:
  image: silex/emacs:29-ci-cask
  stage: test
  script:
    - cd cfn-gen
    - make deps
    - make lint
