default:
  image: silex/emacs:27-dev

lint cfn-mode emacs27:
  stage: test
  script:
    - cd cfn-mode
    - make lint

lint cfn-mode emacs26:
  stage: test
  script:
    - cd cfn-mode
    - make deps
    - make lint
  image: silex/emacs:26-dev

lint flycheck-cfn emacs27:
  stage: test
  script:
    - cd flycheck-cfn
    - make deps
    - make lint

lint flycheck-cfn emacs26:
  stage: test
  script:
    - cd flycheck-cfn
    - make deps
    - make lint
  image: silex/emacs:26-dev
