default:
  image: silex/emacs:27-dev

lint 27:
  script:
    - make deps
    - make lint

lint 26:
  script:
    - make deps
    - make lint
  image: silex/emacs:26-dev

lint 25:
  script:
    - make deps
    - make lint
  image: silex/emacs:25-dev
