default:
  image: silex/emacs:27-ci-cask

lint cfn-mode emacs27:
  stage: test
  script:
    - cd cfn-mode
    - make deps
    - make lint

lint cfn-mode emacs26:
  stage: test
  script:
    - cd cfn-mode
    - make deps
    - make lint
  image: silex/emacs:26-ci-cask

lint cfn-mode emacs-master:
  allow_failure: true
  stage: test
  script:
    - cd cfn-mode
    - make deps
    - make lint
  image: silex/emacs:master-ci-cask

lint flycheck-cfn emacs27:
  stage: test
  script:
    - cd flycheck-cfn
    - make deps
    - make lint

lint flycheck-cfn emacs26:
  stage: test
  script:
    - cd flycheck-cfn
    - make deps
    - make lint
  image: silex/emacs:26-ci-cask

lint flycheck-cfn emacs-master:
  allow_failure: true
  stage: test
  script:
    - cd flycheck-cfn
    - make deps
    - make lint
  image: silex/emacs:master-ci-cask

# only lint this in emacs27. it's dev-only so compat doesn't matter
lint cfn-gen emacs27:
  stage: test
  script:
    - cd cfn-gen
    - make deps
    - make lint
